name: Trigger Target Workflow
on:
  push:
    branches:
      - 'main'
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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" \
            https://api.github.com/repos/DevOpsTeamE/DevOps2023Asg1/dispatches \
            -d "{\"event_type\": \"trigger-workflow\"}"