name: Trigger Target Workflow
on:
  push:
    branches:
      - 'main'
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/DevOpsTeamE/DevOps2023Asg1/actions/workflows/80562802/dispatches -d '{"ref":"main"}'